/**
 * This file is autogenerated by NextDeveloper Generator Module
 * Check our github project to have more information about it;
 * https://github.com/nextdeveloper-nl/generator
 */

namespace {{ $namespace }}\{{ $module }}\Database\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

/**
 * Class {{ $model }}.
 *
 * @package {{ $namespace }}\{{ $module }}\Database\Models
 */
class {{ $model }} extends AbstractModel
{
    /**
     * @var array
     */
    protected $guarded = [];

    /**
     *  Here we have the fulltext fields. We can use these for fulltext search if enabled.
     */
    protected $fullTextFields = [];

    /**
     * @var array
     */
    protected $appends = [];

    /**
     * We are casting fields to objects so that we can work on them better
     * @var array
     */
    protected $casts = [

    ];

    /**
     * We are casting data fields.
     * @var array
     */
    protected $dates = [

    ];

    /**
     * @var array
     */
    protected $with = [

    ];

    /**
     * @var int
     */
    protected $perPage = {{ $perPage }};

    /**
     * @return void
     */
    public static function boot()
    {
        parent::boot();

        //  We create and add Observer even if we wont use it.
        parent::observe(AccountObserver::class);
    }
}
