{
    "name": "{{ strtolower($namespace) }}/{{ strtolower($module) }}",
    "description": "{{ $namespace }} {{ $module }} Package, generated by NextDeveloper Generator.",
    "type": "library",
    "license": "MIT",
    "authors": [
    ],
    "require": {
        "php": ">=8.2.0",
        "league/fractal": "*",
        "monolog/monolog": "*"
    },
    "require-dev": {
        "illuminate/support": "5.5.*",
        "illuminate/database": "5.5.*",
        "illuminate/validation": "5.5.*"
    },
    "autoload": {
        "psr-4": {
            "{{ $namespace }}\\{{ $module }}\\": "src/",
            "{{ $namespace }}\\{{ $module }}\\Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "providers": [
                "{{ $namespace }}\\{{ $module }}\\{{ $module }}ServiceProvider"
            ]
        }
    },
    "suggest": {}
}